#!/usr/bin/env python
# -*- coding: utf-8 -*-

from const import path
from const import items

# ログファイル保存数
KEEP_LOG = 20

# メイン画面色
MAIN_BGCOLOR = '#FFCCFF' if 'Win' == path.PC else '#AAFFAA'
MAIN_ACT_COLOR = ['#FFFF77', '#000000']

# Path
PC = path.PC
PC_NAME = path.PC_NAME
IP = path.IP
WEB_IP = path.WEB_IP
MY_IP = path.MY_IP
DEV_IP = path.DEV_IP
MAC_IP = path.MAC_IP
IPS = path.IPS
IP_LIST = path.IP_LIST
CURRENT_PATH = path.CURRENT_PATH
GDRIVE_PATH = path.GDRIVE_PATH
TEMP_PATH = path.TEMP_PATH
RUN_PATH = path.RUN_PATH
MT4_PATH = path.MT4_PATH
MT4_DEV = path.MT4_DEV
DATA_PATH = path.DATA_PATH
TEST_UNIT = path.TEST_UNIT
TEST_OUT_PATH = path.TEST_OUT_PATH
TEST_LINK = path.TEST_LINK
TICK_STORY = path.TICK_STORY
HST_PATH = path.HST_PATH
ANM_FOLD = path.ANM_FOLD
ANM_PATH = path.ANM_PATH
ANM_OUT_PATH = path.ANM_OUT_PATH
PRM_PATH = path.PRM_PATH
RM_PATH = path.RM_PATH
MATCH_PATH = path.MATCH_PATH
MENU_CSV = path.MENU_CSV
ICON_FILE = path.ICON_FILE

# items
ENG1MIN_MONITOR = items.ENG1MIN_MONITOR
MT4_WAIT = items.MT4_WAIT
MATCH_IMG_MT4 = items.MATCH_IMG_MT4
MATCH_IMG_RM = items.MATCH_IMG_RM
EA_PATHS = items.EA_PATHS
CURRNCYS_EA = items.CURRNCYS_EA
CURRNCYS_365 = items.CURRNCYS_365
EA_DATA_NAMES = items.EA_DATA_NAMES
RATE_CSV = items.RATE_CSV
RATE_REAL = items.RATE_REAL
BLOG_URL = items.BLOG_URL
BLOG_MAIL = items.BLOG_MAIL
BLOG_MAIL_PW = items.BLOG_MAIL_PW
ERROR_MAIL = items.ERROR_MAIL
ERROR_MAIL_PW = items.ERROR_MAIL_PW
TWITTER_ID = items.TWITTER_ID
TWITTER_PW = items.TWITTER_PW
TWITTER_TAG = items.TWITTER_TAG
TWEET_TIME = items.TWEET_TIME
ANM_SPAN = items.ANM_SPAN
ANM_RANGE = items.ANM_RANGE
ANM_AFTER = items.ANM_AFTER
ANM_OPEN = items.ANM_OPEN
ANM_RATE = items.ANM_RATE
ANM_HOUR_UD = items.ANM_HOUR_UD
ANM_DIFF = items.ANM_DIFF
ANM_JUDGE = items.ANM_JUDGE
ANM_BEST = items.ANM_BEST
ANM_REPORT_UD = items.ANM_REPORT_UD
DAY_WEEK = items.DAY_WEEK
ENGLISH_USE_URL = items.ENGLISH_USE_URL
ENGLISH_MASTER_URL = items.ENGLISH_MASTER_URL
ENGLISH_CONTENTS_URL = items.ENGLISH_CONTENTS_URL
ENGLISH_IMAGES_URL = items.ENGLISH_IMAGES_URL
ENGLISH_MASTER_LEVEL = items.ENGLISH_MASTER_LEVEL
ENGLISH_NOUNS = items.ENGLISH_NOUNS
ENGLISH_DICT_URL = items.ENGLISH_DICT_URL
LONGMAN_PARTSPEECH = items.LONGMAN_PARTSPEECH
