#!/usr/bin/env python
# -*- coding: utf-8 -*-

from const import path
from const import items

# ログファイル保存数
KEEP_LOG = 20

# メイン画面色
MAIN_BGCOLOR = '#FFCCFF' if 'Win' == path.PC else '#AAFFAA'
MAIN_ACT_COLOR = ['#FFFF77', '#000000']

# Path
PC = path.PC
PC_NAME = path.PC_NAME
IP = path.IP
WEB_IP = path.WEB_IP
MY_IP = path.MY_IP
DEV_IP = path.DEV_IP
MAC_IP = path.MAC_IP
IPS = path.IPS
MY_LINKS = path.MY_LINKS
CURRENT_PATH = path.CURRENT_PATH
GDRIVE_PATH = path.GDRIVE_PATH
TEMP_PATH = path.TEMP_PATH
RUN_PATH = path.RUN_PATH
MT4_DEV = path.MT4_DEV
DATA_PATH = path.DATA_PATH
TEST_UNIT = path.TEST_UNIT
TEST_OUT_PATH = path.TEST_OUT_PATH
TEST_LINK = path.TEST_LINK
TICK_HISTORY = path.TICK_HISTORY
PRM_PATH = path.PRM_PATH
RM_PATH = path.RM_PATH
MATCH_PATH = path.MATCH_PATH
MENU_CSV = path.MENU_CSV
ICON_FILE = path.ICON_FILE

# items
ENG1MIN_MONITOR = items.ENG1MIN_MONITOR
MT4_WAIT = items.MT4_WAIT
MATCH_IMG_MT4 = items.MATCH_IMG_MT4
MATCH_IMG_RM = items.MATCH_IMG_RM
EA_PATHS = items.EA_PATHS
CURRNCYS_EA = items.CURRNCYS_EA
CURRNCYS_365 = items.CURRNCYS_365
EA_DATA_NAMES = items.EA_DATA_NAMES
BLOG_URL = items.BLOG_URL
BLOG_MAIL = items.BLOG_MAIL
BLOG_MAIL_PW = items.BLOG_MAIL_PW
ERROR_MAIL = items.ERROR_MAIL
ERROR_MAIL_PW = items.ERROR_MAIL_PW
